sudo: false
language: python
cache: pip
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - 3.5-dev
    - pypy
install:
    - pip install -r requirements.txt
script:
    - python setup.py nosetests
after_success:
    - coveralls
